- hosts: server
  vars:
  -  image: rahadiancs/httpd-custom:icon
  tasks:
    - name: install python docker ubuntu
      apt:
        name:
          - python3
          - python3-docker
        state: present
      when:
      - ansible_distribution == "Ubuntu"
    - name: install python docker for centos
      yum:
        name: python-docker
        state: present
      when:
      - ansible_distribution == "CentOS"
    - name: pull images
      docker_image:
        name: "{{ image }}"
        state: present
    - name: create containers
      docker_container:
        name: docker-ansible
        state: started
        published_ports:
          - 8090:80
        image: "{{ image }}"
        recreate: yes
